[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "client/dist"

[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "credentialless"
