packages:
  - bridge
  - client
  - contracts
  - server
  - packages/constants
  - packages/contracts
  - packages/events
  - packages/gamelogic
  - packages/hexgen
  - packages/hashing
  - packages/indexer-core
  - packages/serde
  - packages/utils
  - packages/types
  - packages/procedural
  - packages/renderer
  - packages/ui

# ignoredBuiltDependencies:
#   - esbuild
#   - leveldown
#   - lmdb
#   - msgpackr-extract
#   - protobufjs
