/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import AdminContractArtifactJson from "./admin-Admin.json" with { type: "json" };
export const AdminContractArtifact = loadContractArtifact(
  AdminContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Admin;
 */
export class AdminContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, AdminContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): AdminContract {
    return Contract.at(
      address,
      AdminContract.artifact,
      wallet,
    ) as AdminContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, adminAddress: AztecAddressLike) {
    return new DeployMethod<AdminContract>(
      PublicKeys.default(),
      wallet,
      AdminContractArtifact,
      (instance, wallet) => AdminContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    adminAddress: AztecAddressLike,
  ) {
    return new DeployMethod<AdminContract>(
      publicKeys,
      wallet,
      AdminContractArtifact,
      (instance, wallet) => AdminContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AdminContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AdminContract["methods"][M]>
  ) {
    return new DeployMethod<AdminContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AdminContractArtifact,
      (instance, wallet) => AdminContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AdminContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      AdminContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "config_storage_address"
    | "world_storage_address"
    | "player_storage_address"
    | "planet_storage_address"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      config_storage_address: {
        slot: new Fr(2n),
      },
      world_storage_address: {
        slot: new Fr(3n),
      },
      player_storage_address: {
        slot: new Fr(4n),
      },
      planet_storage_address: {
        slot: new Fr(5n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "config_storage_address"
      | "world_storage_address"
      | "player_storage_address"
      | "planet_storage_address"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** add_score(player_address: struct, player_state: struct, amount: integer) */
    add_score: ((
      player_address: AztecAddressLike,
      player_state: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** admin_initialize_planet(location_id: field, perlin: integer, level: integer) */
    admin_initialize_planet: ((
      location_id: FieldLike,
      perlin: bigint | number,
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** admin_set_world_radius(new_radius: integer, world: struct) */
    admin_set_world_radius: ((
      new_radius: bigint | number,
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(adminAddress: struct) */
    constructor: ((
      adminAddress: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** create_planet(args: struct) */
    create_planet: ((args: {
      location: FieldLike;
      perlin: bigint | number;
      level: bigint | number;
      planet_type: bigint | number;
      require_valid_location_id: boolean;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** deduct_score(player_address: struct, player_state: struct, amount: integer) */
    deduct_score: ((
      player_address: AztecAddressLike,
      player_state: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** pause(world: struct) */
    pause: ((world: {
      paused: boolean;
      radius: bigint | number;
      misc_nonce: bigint | number;
      next_change_block: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** safe_set_owner(x: field, y: field, location_id: field, perlin: integer, level: integer, new_owner: struct, timestamp: integer, provided_snark_config: struct, planet_default_stats: struct, world_config: struct, game_config_core: struct, planet_level_thresholds: struct, space_junk_config: struct, planet_type_weights_tier_0: struct, planet_type_weights_tier_1: struct, planet_type_weights_tier_2: struct, planet_type_weights_tier_3: struct, world_state: struct, planet_state: struct) */
    safe_set_owner: ((
      x: FieldLike,
      y: FieldLike,
      location_id: FieldLike,
      perlin: bigint | number,
      level: bigint | number,
      new_owner: AztecAddressLike,
      timestamp: bigint | number,
      provided_snark_config: {
        disable_zk_checks: boolean;
        planethash_key: bigint | number;
        spacetype_key: bigint | number;
        biomebase_key: bigint | number;
        perlin_mirror_x: boolean;
        perlin_mirror_y: boolean;
        perlin_length_scale: bigint | number;
      },
      planet_default_stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      },
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      game_config_core: {
        max_natural_planet_level: bigint | number;
        perlin_threshold_1: bigint | number;
        perlin_threshold_2: bigint | number;
        perlin_threshold_3: bigint | number;
        init_perlin_min: bigint | number;
        init_perlin_max: bigint | number;
        biome_threshold_1: bigint | number;
        biome_threshold_2: bigint | number;
        planet_rarity: bigint | number;
        max_location_id: FieldLike;
      },
      planet_level_thresholds: { thresholds: (bigint | number)[] },
      space_junk_config: {
        space_junk_enabled: boolean;
        space_junk_limit: bigint | number;
        planet_level_junk: (bigint | number)[];
        abandon_speed_change_percent: bigint | number;
        abandon_range_change_percent: bigint | number;
      },
      planet_type_weights_tier_0: { weights: (bigint | number)[][] },
      planet_type_weights_tier_1: { weights: (bigint | number)[][] },
      planet_type_weights_tier_2: { weights: (bigint | number)[][] },
      planet_type_weights_tier_3: { weights: (bigint | number)[][] },
      world_state: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_all_storage_addresses(config_addr: struct, world_addr: struct, player_addr: struct, planet_addr: struct) */
    set_all_storage_addresses: ((
      config_addr: AztecAddressLike,
      world_addr: AztecAddressLike,
      player_addr: AztecAddressLike,
      planet_addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_config_storage_address(config_storage_address: struct) */
    set_config_storage_address: ((
      config_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_owner(planet_id: field, planet_state: struct, new_owner: struct) */
    set_owner: ((
      planet_id: FieldLike,
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      new_owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_storage_address(planet_storage_address: struct) */
    set_planet_storage_address: ((
      planet_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_player_storage_address(player_storage_address: struct) */
    set_player_storage_address: ((
      player_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_world_storage_address(world_storage_address: struct) */
    set_world_storage_address: ((
      world_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** unpause(world: struct) */
    unpause: ((world: {
      paused: boolean;
      radius: bigint | number;
      misc_nonce: bigint | number;
      next_change_block: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
