/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import ArrivalStorageContractArtifactJson from "./arrival-ArrivalStorage.json" with { type: "json" };
export const ArrivalStorageContractArtifact = loadContractArtifact(
  ArrivalStorageContractArtifactJson as NoirCompiledContract,
);

export type ArrivalUpdate = {
  id: FieldLike;
  block_number: bigint | number;
  state: {
    id: FieldLike;
    player: AztecAddressLike;
    from_planet: FieldLike;
    to_planet: FieldLike;
    pop_arriving: bigint | number;
    silver_moved: bigint | number;
    departure_time: bigint | number;
    arrival_time: bigint | number;
    arrival_type: bigint | number;
    carried_artifact_id: FieldLike;
    distance: bigint | number;
  };
};

/**
 * Type-safe interface for contract ArrivalStorage;
 */
export class ArrivalStorageContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, ArrivalStorageContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ArrivalStorageContract {
    return Contract.at(
      address,
      ArrivalStorageContract.artifact,
      wallet,
    ) as ArrivalStorageContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ArrivalStorageContract>(
      PublicKeys.default(),
      wallet,
      ArrivalStorageContractArtifact,
      (instance, wallet) => ArrivalStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<ArrivalStorageContract>(
      publicKeys,
      wallet,
      ArrivalStorageContractArtifact,
      (instance, wallet) => ArrivalStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof ArrivalStorageContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ArrivalStorageContract["methods"][M]>
  ) {
    return new DeployMethod<ArrivalStorageContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ArrivalStorageContractArtifact,
      (instance, wallet) => ArrivalStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ArrivalStorageContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      ArrivalStorageContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "authorized_map"
    | "authorized_index"
    | "authorized_list"
    | "authorized_count"
    | "state_roots"
    | "stored_arrivals"
    | "event_id_counter"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      authorized_map: {
        slot: new Fr(2n),
      },
      authorized_index: {
        slot: new Fr(3n),
      },
      authorized_list: {
        slot: new Fr(4n),
      },
      authorized_count: {
        slot: new Fr(5n),
      },
      state_roots: {
        slot: new Fr(6n),
      },
      stored_arrivals: {
        slot: new Fr(7n),
      },
      event_id_counter: {
        slot: new Fr(8n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "authorized_map"
      | "authorized_index"
      | "authorized_list"
      | "authorized_count"
      | "state_roots"
      | "stored_arrivals"
      | "event_id_counter"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** add_authorized_contract(contract_address: struct) */
    add_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** add_authorized_contracts_batch(addresses: array, count: integer) */
    add_authorized_contracts_batch: ((
      addresses: AztecAddressLike[],
      count: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** allocate_event_id() */
    allocate_event_id: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash(state: struct) */
    compute_state_hash: ((state: {
      id: FieldLike;
      player: AztecAddressLike;
      from_planet: FieldLike;
      to_planet: FieldLike;
      pop_arriving: bigint | number;
      silver_moved: bigint | number;
      departure_time: bigint | number;
      arrival_time: bigint | number;
      arrival_type: bigint | number;
      carried_artifact_id: FieldLike;
      distance: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash_unconstrained(state: struct) */
    compute_state_hash_unconstrained: ((state: {
      id: FieldLike;
      player: AztecAddressLike;
      from_planet: FieldLike;
      to_planet: FieldLike;
      pop_arriving: bigint | number;
      silver_moved: bigint | number;
      departure_time: bigint | number;
      arrival_time: bigint | number;
      arrival_type: bigint | number;
      carried_artifact_id: FieldLike;
      distance: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_arrival(id: field) */
    get_arrival: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_arrival_unconstrained(id: field) */
    get_arrival_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract(index: integer) */
    get_authorized_contract: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract_unconstrained(index: integer) */
    get_authorized_contract_unconstrained: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count() */
    get_authorized_count: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count_unconstrained() */
    get_authorized_count_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_default_state_unconstrained() */
    get_default_state_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_event_id_counter_unconstrained() */
    get_event_id_counter_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root(id: field) */
    get_state_root: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root_unconstrained(id: field) */
    get_state_root_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized(addr: struct) */
    is_authorized: ((addr: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized_unconstrained(addr: struct) */
    is_authorized_unconstrained: ((
      addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized(id: field) */
    is_initialized: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized_unconstrained(id: field) */
    is_initialized_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** remove_authorized_contract(contract_address: struct) */
    remove_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set(id: field, state: struct) */
    set: ((
      id: FieldLike,
      state: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify(id: field, state: struct) */
    verify: ((
      id: FieldLike,
      state: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_hash(id: field, hash: field) */
    verify_hash: ((
      id: FieldLike,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_hashes_batch(ids: array, hashes: array, count: integer) */
    verify_hashes_batch: ((
      ids: FieldLike[],
      hashes: FieldLike[],
      count: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_unconstrained(id: field, state: struct) */
    verify_unconstrained: ((
      id: FieldLike,
      state: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };

  public static get events(): {
    ArrivalUpdate: {
      abiType: AbiType;
      eventSelector: EventSelector;
      fieldNames: string[];
    };
  } {
    return {
      ArrivalUpdate: {
        abiType: {
          kind: "struct",
          fields: [
            {
              name: "id",
              type: {
                kind: "field",
              },
            },
            {
              name: "block_number",
              type: {
                kind: "integer",
                sign: "unsigned",
                width: 32,
              },
            },
            {
              name: "state",
              type: {
                kind: "struct",
                fields: [
                  {
                    name: "id",
                    type: {
                      kind: "field",
                    },
                  },
                  {
                    name: "player",
                    type: {
                      kind: "struct",
                      fields: [
                        {
                          name: "inner",
                          type: {
                            kind: "field",
                          },
                        },
                      ],
                      path: "aztec::protocol_types::address::aztec_address::AztecAddress",
                    },
                  },
                  {
                    name: "from_planet",
                    type: {
                      kind: "field",
                    },
                  },
                  {
                    name: "to_planet",
                    type: {
                      kind: "field",
                    },
                  },
                  {
                    name: "pop_arriving",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "silver_moved",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "departure_time",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 64,
                    },
                  },
                  {
                    name: "arrival_time",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 64,
                    },
                  },
                  {
                    name: "arrival_type",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "carried_artifact_id",
                    type: {
                      kind: "field",
                    },
                  },
                  {
                    name: "distance",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                ],
                path: "types::storage::arrival::Arrival",
              },
            },
          ],
          path: "ArrivalStorage::ArrivalUpdate",
        },
        eventSelector: EventSelector.fromString("0x72e36f34"),
        fieldNames: ["id", "block_number", "state"],
      },
    };
  }
}
