/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import ArtifactFindContractArtifactJson from "./artifact_find-ArtifactFind.json" with { type: "json" };
export const ArtifactFindContractArtifact = loadContractArtifact(
  ArtifactFindContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract ArtifactFind;
 */
export class ArtifactFindContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, ArtifactFindContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ArtifactFindContract {
    return Contract.at(
      address,
      ArtifactFindContract.artifact,
      wallet,
    ) as ArtifactFindContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ArtifactFindContract>(
      PublicKeys.default(),
      wallet,
      ArtifactFindContractArtifact,
      (instance, wallet) => ArtifactFindContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<ArtifactFindContract>(
      publicKeys,
      wallet,
      ArtifactFindContractArtifact,
      (instance, wallet) => ArtifactFindContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ArtifactFindContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ArtifactFindContract["methods"][M]>
  ) {
    return new DeployMethod<ArtifactFindContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ArtifactFindContractArtifact,
      (instance, wallet) => ArtifactFindContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ArtifactFindContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      ArtifactFindContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "config_storage_address"
    | "arrivals_storage_address"
    | "artifact_storage_address"
    | "artifact_location_storage_address"
    | "planet_storage_address"
    | "planet_artifacts_storage_address"
    | "planet_events_storage_address"
    | "player_storage_address"
    | "world_storage_address"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      config_storage_address: {
        slot: new Fr(2n),
      },
      arrivals_storage_address: {
        slot: new Fr(3n),
      },
      artifact_storage_address: {
        slot: new Fr(4n),
      },
      artifact_location_storage_address: {
        slot: new Fr(5n),
      },
      planet_storage_address: {
        slot: new Fr(6n),
      },
      planet_artifacts_storage_address: {
        slot: new Fr(7n),
      },
      planet_events_storage_address: {
        slot: new Fr(8n),
      },
      player_storage_address: {
        slot: new Fr(9n),
      },
      world_storage_address: {
        slot: new Fr(10n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "config_storage_address"
      | "arrivals_storage_address"
      | "artifact_storage_address"
      | "artifact_location_storage_address"
      | "planet_storage_address"
      | "planet_artifacts_storage_address"
      | "planet_events_storage_address"
      | "player_storage_address"
      | "world_storage_address"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** find_artifact(location_id: field, x: field, y: field, biomebase: integer, timestamp: integer, provided_snark_config: struct, game_config_core: struct, world_config: struct, artifacts_config: struct, spaceships_config: struct, player: struct, planet: struct, planet_events_state: struct, arrivals: array, arrival_artifacts: array, arrival_artifact_locations: array, planet_artifacts_state: struct, owned_artifacts: array, owned_artifact_locations: array, world: struct) */
    find_artifact: ((
      location_id: FieldLike,
      x: FieldLike,
      y: FieldLike,
      biomebase: bigint | number,
      timestamp: bigint | number,
      provided_snark_config: {
        disable_zk_checks: boolean;
        planethash_key: bigint | number;
        spacetype_key: bigint | number;
        biomebase_key: bigint | number;
        perlin_mirror_x: boolean;
        perlin_mirror_y: boolean;
        perlin_length_scale: bigint | number;
      },
      game_config_core: {
        max_natural_planet_level: bigint | number;
        perlin_threshold_1: bigint | number;
        perlin_threshold_2: bigint | number;
        perlin_threshold_3: bigint | number;
        init_perlin_min: bigint | number;
        init_perlin_max: bigint | number;
        biome_threshold_1: bigint | number;
        biome_threshold_2: bigint | number;
        planet_rarity: bigint | number;
        max_location_id: FieldLike;
      },
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      artifacts_config: {
        token_mint_end_timestamp: bigint | number;
        artifact_point_values: (bigint | number)[];
        photoid_activation_delay: bigint | number;
      },
      spaceships_config: {
        gear: boolean;
        mothership: boolean;
        titan: boolean;
        crescent: boolean;
        whale: boolean;
      },
      player: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      planet: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      owned_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      owned_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_all_storage_addresses(config_storage_address: struct, arrivals_storage_address: struct, artifact_storage_address: struct, artifact_location_storage_address: struct, planet_storage_address: struct, planet_artifacts_storage_address: struct, planet_events_storage_address: struct, player_storage_address: struct, world_storage_address: struct) */
    set_all_storage_addresses: ((
      config_storage_address: AztecAddressLike,
      arrivals_storage_address: AztecAddressLike,
      artifact_storage_address: AztecAddressLike,
      artifact_location_storage_address: AztecAddressLike,
      planet_storage_address: AztecAddressLike,
      planet_artifacts_storage_address: AztecAddressLike,
      planet_events_storage_address: AztecAddressLike,
      player_storage_address: AztecAddressLike,
      world_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_arrivals_storage_address(arrivals_storage_address: struct) */
    set_arrivals_storage_address: ((
      arrivals_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_location_storage_address(artifact_location_storage_address: struct) */
    set_artifact_location_storage_address: ((
      artifact_location_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_storage_address(artifact_storage_address: struct) */
    set_artifact_storage_address: ((
      artifact_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_config_storage_address(config_storage_address: struct) */
    set_config_storage_address: ((
      config_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_artifacts_storage_address(planet_artifacts_storage_address: struct) */
    set_planet_artifacts_storage_address: ((
      planet_artifacts_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_events_storage_address(planet_events_storage_address: struct) */
    set_planet_events_storage_address: ((
      planet_events_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_storage_address(planet_storage_address: struct) */
    set_planet_storage_address: ((
      planet_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_player_storage_address(player_storage_address: struct) */
    set_player_storage_address: ((
      player_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_world_storage_address(world_storage_address: struct) */
    set_world_storage_address: ((
      world_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
