/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import ConfigContractArtifactJson from "./config-Config.json" with { type: "json" };
export const ConfigContractArtifact = loadContractArtifact(
  ConfigContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Config;
 */
export class ConfigContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, ConfigContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): ConfigContract {
    return Contract.at(
      address,
      ConfigContract.artifact,
      wallet,
    ) as ConfigContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ConfigContract>(
      PublicKeys.default(),
      wallet,
      ConfigContractArtifact,
      (instance, wallet) => ConfigContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<ConfigContract>(
      publicKeys,
      wallet,
      ConfigContractArtifact,
      (instance, wallet) => ConfigContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ConfigContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ConfigContract["methods"][M]>
  ) {
    return new DeployMethod<ConfigContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ConfigContractArtifact,
      (instance, wallet) => ConfigContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ConfigContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      ConfigContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "world_config"
    | "snark_config"
    | "game_config_core"
    | "planet_level_thresholds"
    | "planet_type_weights_tier_0"
    | "planet_type_weights_tier_1"
    | "planet_type_weights_tier_2"
    | "planet_type_weights_tier_3"
    | "artifacts_config"
    | "spaceships_config"
    | "space_junk_config"
    | "capture_zones_config"
    | "upgrade_config"
    | "world_config_hash"
    | "snark_config_hash"
    | "game_config_core_hash"
    | "planet_level_thresholds_hash"
    | "planet_type_weights_tier_0_hash"
    | "planet_type_weights_tier_1_hash"
    | "planet_type_weights_tier_2_hash"
    | "planet_type_weights_tier_3_hash"
    | "artifacts_config_hash"
    | "spaceships_config_hash"
    | "space_junk_config_hash"
    | "capture_zones_config_hash"
    | "upgrade_config_hash"
    | "planet_default_stats_hash"
    | "planet_default_stats"
    | "upgrades"
    | "upgrades_hash"
    | "cumulative_rarities"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      world_config: {
        slot: new Fr(2n),
      },
      snark_config: {
        slot: new Fr(11n),
      },
      game_config_core: {
        slot: new Fr(18n),
      },
      planet_level_thresholds: {
        slot: new Fr(28n),
      },
      planet_type_weights_tier_0: {
        slot: new Fr(38n),
      },
      planet_type_weights_tier_1: {
        slot: new Fr(88n),
      },
      planet_type_weights_tier_2: {
        slot: new Fr(138n),
      },
      planet_type_weights_tier_3: {
        slot: new Fr(188n),
      },
      artifacts_config: {
        slot: new Fr(238n),
      },
      spaceships_config: {
        slot: new Fr(246n),
      },
      space_junk_config: {
        slot: new Fr(251n),
      },
      capture_zones_config: {
        slot: new Fr(265n),
      },
      upgrade_config: {
        slot: new Fr(280n),
      },
      world_config_hash: {
        slot: new Fr(286n),
      },
      snark_config_hash: {
        slot: new Fr(287n),
      },
      game_config_core_hash: {
        slot: new Fr(288n),
      },
      planet_level_thresholds_hash: {
        slot: new Fr(289n),
      },
      planet_type_weights_tier_0_hash: {
        slot: new Fr(290n),
      },
      planet_type_weights_tier_1_hash: {
        slot: new Fr(291n),
      },
      planet_type_weights_tier_2_hash: {
        slot: new Fr(292n),
      },
      planet_type_weights_tier_3_hash: {
        slot: new Fr(293n),
      },
      artifacts_config_hash: {
        slot: new Fr(294n),
      },
      spaceships_config_hash: {
        slot: new Fr(295n),
      },
      space_junk_config_hash: {
        slot: new Fr(296n),
      },
      capture_zones_config_hash: {
        slot: new Fr(297n),
      },
      upgrade_config_hash: {
        slot: new Fr(298n),
      },
      planet_default_stats_hash: {
        slot: new Fr(299n),
      },
      planet_default_stats: {
        slot: new Fr(300n),
      },
      upgrades: {
        slot: new Fr(301n),
      },
      upgrades_hash: {
        slot: new Fr(302n),
      },
      cumulative_rarities: {
        slot: new Fr(303n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "world_config"
      | "snark_config"
      | "game_config_core"
      | "planet_level_thresholds"
      | "planet_type_weights_tier_0"
      | "planet_type_weights_tier_1"
      | "planet_type_weights_tier_2"
      | "planet_type_weights_tier_3"
      | "artifacts_config"
      | "spaceships_config"
      | "space_junk_config"
      | "capture_zones_config"
      | "upgrade_config"
      | "world_config_hash"
      | "snark_config_hash"
      | "game_config_core_hash"
      | "planet_level_thresholds_hash"
      | "planet_type_weights_tier_0_hash"
      | "planet_type_weights_tier_1_hash"
      | "planet_type_weights_tier_2_hash"
      | "planet_type_weights_tier_3_hash"
      | "artifacts_config_hash"
      | "spaceships_config_hash"
      | "space_junk_config_hash"
      | "capture_zones_config_hash"
      | "upgrade_config_hash"
      | "planet_default_stats_hash"
      | "planet_default_stats"
      | "upgrades"
      | "upgrades_hash"
      | "cumulative_rarities"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** admin_address_unconstrained() */
    admin_address_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_all_config_hashes_unconstrained() */
    get_all_config_hashes_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_all_planet_default_stats_hashes() */
    get_all_planet_default_stats_hashes: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_all_planet_default_stats_hashes_unconstrained() */
    get_all_planet_default_stats_hashes_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artifact_point_values_unconstrained() */
    get_artifact_point_values_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artifacts_config() */
    get_artifacts_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artifacts_config_hash() */
    get_artifacts_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artifacts_config_hash_unconstrained() */
    get_artifacts_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artifacts_config_unconstrained() */
    get_artifacts_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_capture_zones_config() */
    get_capture_zones_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_capture_zones_config_hash() */
    get_capture_zones_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_capture_zones_config_hash_unconstrained() */
    get_capture_zones_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_capture_zones_config_unconstrained() */
    get_capture_zones_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_cumulative_rarity(index: integer) */
    get_cumulative_rarity: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_cumulative_rarity_unconstrained(index: integer) */
    get_cumulative_rarity_unconstrained: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_default_stats_unconstrained() */
    get_default_stats_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_game_config_core() */
    get_game_config_core: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_game_config_core_hash() */
    get_game_config_core_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_game_config_core_hash_unconstrained() */
    get_game_config_core_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_game_config_core_unconstrained() */
    get_game_config_core_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_default_stats(level: integer) */
    get_planet_default_stats: ((
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_default_stats_hash(level: integer) */
    get_planet_default_stats_hash: ((
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_default_stats_hash_unconstrained(level: integer) */
    get_planet_default_stats_hash_unconstrained: ((
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_default_stats_unconstrained(level: integer) */
    get_planet_default_stats_unconstrained: ((
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_init_config(level: integer) */
    get_planet_init_config: ((
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_level_thresholds() */
    get_planet_level_thresholds: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_level_thresholds_hash() */
    get_planet_level_thresholds_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_level_thresholds_hash_unconstrained() */
    get_planet_level_thresholds_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_level_thresholds_unconstrained() */
    get_planet_level_thresholds_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_type_weights_tier(tier: integer) */
    get_planet_type_weights_tier: ((
      tier: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_type_weights_tier_hash(tier: integer) */
    get_planet_type_weights_tier_hash: ((
      tier: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_type_weights_tier_hash_unconstrained(tier: integer) */
    get_planet_type_weights_tier_hash_unconstrained: ((
      tier: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_planet_type_weights_tier_unconstrained(tier: integer) */
    get_planet_type_weights_tier_unconstrained: ((
      tier: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_reveal_cooldown_unconstrained() */
    get_reveal_cooldown_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_snark_config() */
    get_snark_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_snark_config_hash() */
    get_snark_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_snark_config_hash_unconstrained() */
    get_snark_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_snark_config_unconstrained() */
    get_snark_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_space_junk_config() */
    get_space_junk_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_space_junk_config_hash() */
    get_space_junk_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_space_junk_config_hash_unconstrained() */
    get_space_junk_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_space_junk_config_unconstrained() */
    get_space_junk_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_spaceships_config() */
    get_spaceships_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_spaceships_config_hash() */
    get_spaceships_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_spaceships_config_hash_unconstrained() */
    get_spaceships_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_spaceships_config_unconstrained() */
    get_spaceships_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_type_weights_unconstrained() */
    get_type_weights_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade(key: integer) */
    get_upgrade: ((key: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_by_branch_level(branch: integer, level: integer) */
    get_upgrade_by_branch_level: ((
      branch: bigint | number,
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_by_branch_level_unconstrained(branch: integer, level: integer) */
    get_upgrade_by_branch_level_unconstrained: ((
      branch: bigint | number,
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_config() */
    get_upgrade_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_config_hash() */
    get_upgrade_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_config_hash_unconstrained() */
    get_upgrade_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_config_unconstrained() */
    get_upgrade_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_hash(key: integer) */
    get_upgrade_hash: ((key: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_hash_by_branch_level(branch: integer, level: integer) */
    get_upgrade_hash_by_branch_level: ((
      branch: bigint | number,
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_hash_by_branch_level_unconstrained(branch: integer, level: integer) */
    get_upgrade_hash_by_branch_level_unconstrained: ((
      branch: bigint | number,
      level: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_hash_unconstrained(key: integer) */
    get_upgrade_hash_unconstrained: ((
      key: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrade_unconstrained(key: integer) */
    get_upgrade_unconstrained: ((
      key: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_upgrades_unconstrained() */
    get_upgrades_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_world_config() */
    get_world_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_world_config_hash() */
    get_world_config_hash: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_world_config_hash_unconstrained() */
    get_world_config_hash_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_world_config_unconstrained() */
    get_world_config_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize_cumulative_rarities() */
    initialize_cumulative_rarities: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize_upgrades_defense() */
    initialize_upgrades_defense: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize_upgrades_range() */
    initialize_upgrades_range: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize_upgrades_speed() */
    initialize_upgrades_speed: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifacts_config(config: struct) */
    set_artifacts_config: ((config: {
      token_mint_end_timestamp: bigint | number;
      artifact_point_values: (bigint | number)[];
      photoid_activation_delay: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_capture_zones_config(config: struct) */
    set_capture_zones_config: ((config: {
      capture_zones_enabled: boolean;
      capture_zone_change_block_interval: bigint | number;
      capture_zone_radius: bigint | number;
      capture_zone_planet_level_score: (bigint | number)[];
      capture_zone_hold_blocks_required: bigint | number;
      capture_zones_per_5000_world_radius: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_default_configs_batch_1() */
    set_default_configs_batch_1: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_default_configs_batch_2() */
    set_default_configs_batch_2: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_default_game_config_planet_type_weights_tier(tier: integer) */
    set_default_game_config_planet_type_weights_tier: ((
      tier: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_default_upgrade_config() */
    set_default_upgrade_config: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_game_config_core(config: struct) */
    set_game_config_core: ((config: {
      max_natural_planet_level: bigint | number;
      perlin_threshold_1: bigint | number;
      perlin_threshold_2: bigint | number;
      perlin_threshold_3: bigint | number;
      init_perlin_min: bigint | number;
      init_perlin_max: bigint | number;
      biome_threshold_1: bigint | number;
      biome_threshold_2: bigint | number;
      planet_rarity: bigint | number;
      max_location_id: FieldLike;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_default_stats(level: integer, stats: struct) */
    set_planet_default_stats: ((
      level: bigint | number,
      stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_default_stats_batch(levels: array, stats: array, count: integer) */
    set_planet_default_stats_batch: ((
      levels: (bigint | number)[],
      stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      }[],
      count: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_level_thresholds(config: struct) */
    set_planet_level_thresholds: ((config: {
      thresholds: (bigint | number)[];
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_type_weights_tier(tier: integer, config: struct) */
    set_planet_type_weights_tier: ((
      tier: bigint | number,
      config: { weights: (bigint | number)[][] },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_snark_config(config: struct) */
    set_snark_config: ((config: {
      disable_zk_checks: boolean;
      planethash_key: bigint | number;
      spacetype_key: bigint | number;
      biomebase_key: bigint | number;
      perlin_mirror_x: boolean;
      perlin_mirror_y: boolean;
      perlin_length_scale: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_space_junk_config(config: struct) */
    set_space_junk_config: ((config: {
      space_junk_enabled: boolean;
      space_junk_limit: bigint | number;
      planet_level_junk: (bigint | number)[];
      abandon_speed_change_percent: bigint | number;
      abandon_range_change_percent: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_spaceships_config(config: struct) */
    set_spaceships_config: ((config: {
      gear: boolean;
      mothership: boolean;
      titan: boolean;
      crescent: boolean;
      whale: boolean;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_upgrade(key: integer, upgrade: struct) */
    set_upgrade: ((
      key: bigint | number,
      upgrade: {
        pop_cap_multiplier: bigint | number;
        pop_gro_multiplier: bigint | number;
        range_multiplier: bigint | number;
        speed_multiplier: bigint | number;
        def_multiplier: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_upgrade_by_branch_level(branch: integer, level: integer, upgrade: struct) */
    set_upgrade_by_branch_level: ((
      branch: bigint | number,
      level: bigint | number,
      upgrade: {
        pop_cap_multiplier: bigint | number;
        pop_gro_multiplier: bigint | number;
        range_multiplier: bigint | number;
        speed_multiplier: bigint | number;
        def_multiplier: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_upgrade_config(config: struct) */
    set_upgrade_config: ((config: {
      silver_cost_percent: bigint | number;
      max_total_level_nebula: bigint | number;
      max_total_level_space: bigint | number;
      max_total_level_deep_space: bigint | number;
      max_total_level_dead_space: bigint | number;
      max_branch_level: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_world_config(config: struct) */
    set_world_config: ((config: {
      start_paused: boolean;
      time_factor_hundredths: bigint | number;
      spawn_rim_area: bigint | number;
      world_radius_locked: boolean;
      world_radius_min: bigint | number;
      location_reveal_cooldown: bigint | number;
      silver_score_value: bigint | number;
      planet_transfer_enabled: boolean;
      admin_can_add_planets: boolean;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_all_planet_default_stats_hashes(hashes: array) */
    verify_all_planet_default_stats_hashes: ((
      hashes: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_artifacts_config_hash(hash: field) */
    verify_artifacts_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_capture_zones_config_hash(hash: field) */
    verify_capture_zones_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_config_hashes(level: integer, planet_default_stats_hash: field, hashes: array) */
    verify_config_hashes: ((
      level: bigint | number,
      planet_default_stats_hash: FieldLike,
      hashes: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_game_config_core_hash(hash: field) */
    verify_game_config_core_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_planet_default_stats_hash(level: integer, hash: field) */
    verify_planet_default_stats_hash: ((
      level: bigint | number,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_planet_level_thresholds_hash(hash: field) */
    verify_planet_level_thresholds_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_planet_type_weights_tier_hash(tier: integer, hash: field) */
    verify_planet_type_weights_tier_hash: ((
      tier: bigint | number,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_snark_config_hash(hash: field) */
    verify_snark_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_space_junk_config_hash(hash: field) */
    verify_space_junk_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_spaceships_config_hash(hash: field) */
    verify_spaceships_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_upgrade_config_hash(hash: field) */
    verify_upgrade_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_upgrade_hash(key: integer, hash: field) */
    verify_upgrade_hash: ((
      key: bigint | number,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_upgrade_hash_by_branch_level(branch: integer, level: integer, hash: field) */
    verify_upgrade_hash_by_branch_level: ((
      branch: bigint | number,
      level: bigint | number,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_world_config_hash(hash: field) */
    verify_world_config_hash: ((
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
