/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import CoreContractArtifactJson from "./core-Core.json" with { type: "json" };
export const CoreContractArtifact = loadContractArtifact(
  CoreContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Core;
 */
export class CoreContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, CoreContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): CoreContract {
    return Contract.at(address, CoreContract.artifact, wallet) as CoreContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<CoreContract>(
      PublicKeys.default(),
      wallet,
      CoreContractArtifact,
      (instance, wallet) => CoreContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<CoreContract>(
      publicKeys,
      wallet,
      CoreContractArtifact,
      (instance, wallet) => CoreContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CoreContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CoreContract["methods"][M]>
  ) {
    return new DeployMethod<CoreContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CoreContractArtifact,
      (instance, wallet) => CoreContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CoreContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      CoreContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "config_storage_address"
    | "world_storage_address"
    | "player_storage_address"
    | "planet_storage_address"
    | "planet_revealed_coords_storage_address"
    | "planet_events_storage_address"
    | "planet_artifacts_storage_address"
    | "arrivals_storage_address"
    | "artifact_storage_address"
    | "artifact_location_storage_address"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      config_storage_address: {
        slot: new Fr(2n),
      },
      world_storage_address: {
        slot: new Fr(3n),
      },
      player_storage_address: {
        slot: new Fr(4n),
      },
      planet_storage_address: {
        slot: new Fr(5n),
      },
      planet_revealed_coords_storage_address: {
        slot: new Fr(6n),
      },
      planet_events_storage_address: {
        slot: new Fr(7n),
      },
      planet_artifacts_storage_address: {
        slot: new Fr(8n),
      },
      arrivals_storage_address: {
        slot: new Fr(9n),
      },
      artifact_storage_address: {
        slot: new Fr(10n),
      },
      artifact_location_storage_address: {
        slot: new Fr(11n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "config_storage_address"
      | "world_storage_address"
      | "player_storage_address"
      | "planet_storage_address"
      | "planet_revealed_coords_storage_address"
      | "planet_events_storage_address"
      | "planet_artifacts_storage_address"
      | "arrivals_storage_address"
      | "artifact_storage_address"
      | "artifact_location_storage_address"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize_player(x: field, y: field, radius: integer, location_id: field, perlin: integer, level: integer, timestamp: integer, provided_snark_config: struct, planet_default_stats: struct, world_config: struct, game_config_core: struct, planet_level_thresholds: struct, space_junk_config: struct, planet_type_weights_tier_0: struct, planet_type_weights_tier_1: struct, planet_type_weights_tier_2: struct, planet_type_weights_tier_3: struct, planet_state: struct, planet_events_state: struct, planet_artifacts_state: struct, arrivals: array, arrival_artifacts: array, arrival_artifact_locations: array, player_state: struct, world: struct) */
    initialize_player: ((
      x: FieldLike,
      y: FieldLike,
      radius: bigint | number,
      location_id: FieldLike,
      perlin: bigint | number,
      level: bigint | number,
      timestamp: bigint | number,
      provided_snark_config: {
        disable_zk_checks: boolean;
        planethash_key: bigint | number;
        spacetype_key: bigint | number;
        biomebase_key: bigint | number;
        perlin_mirror_x: boolean;
        perlin_mirror_y: boolean;
        perlin_length_scale: bigint | number;
      },
      planet_default_stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      },
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      game_config_core: {
        max_natural_planet_level: bigint | number;
        perlin_threshold_1: bigint | number;
        perlin_threshold_2: bigint | number;
        perlin_threshold_3: bigint | number;
        init_perlin_min: bigint | number;
        init_perlin_max: bigint | number;
        biome_threshold_1: bigint | number;
        biome_threshold_2: bigint | number;
        planet_rarity: bigint | number;
        max_location_id: FieldLike;
      },
      planet_level_thresholds: { thresholds: (bigint | number)[] },
      space_junk_config: {
        space_junk_enabled: boolean;
        space_junk_limit: bigint | number;
        planet_level_junk: (bigint | number)[];
        abandon_speed_change_percent: bigint | number;
        abandon_range_change_percent: bigint | number;
      },
      planet_type_weights_tier_0: { weights: (bigint | number)[][] },
      planet_type_weights_tier_1: { weights: (bigint | number)[][] },
      planet_type_weights_tier_2: { weights: (bigint | number)[][] },
      planet_type_weights_tier_3: { weights: (bigint | number)[][] },
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      player_state: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** refresh_planet(location: field, planet: struct, planet_artifacts_state: struct, planet_events_state: struct, arrivals: array, arrival_artifacts: array, arrival_artifact_locations: array, timestamp: integer) */
    refresh_planet: ((
      location: FieldLike,
      planet: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      timestamp: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** reveal_location(location: field, perlin: integer, level: integer, x: field, y: field, timestamp: integer, is_admin: boolean, provided_snark_config: struct, planet_default_stats: struct, world_config: struct, game_config_core: struct, planet_level_thresholds: struct, space_junk_config: struct, planet_type_weights_tier_0: struct, planet_type_weights_tier_1: struct, planet_type_weights_tier_2: struct, planet_type_weights_tier_3: struct, planet_state: struct, planet_revealed_coords: struct, player_state: struct, world: struct) */
    reveal_location: ((
      location: FieldLike,
      perlin: bigint | number,
      level: bigint | number,
      x: FieldLike,
      y: FieldLike,
      timestamp: bigint | number,
      is_admin: boolean,
      provided_snark_config: {
        disable_zk_checks: boolean;
        planethash_key: bigint | number;
        spacetype_key: bigint | number;
        biomebase_key: bigint | number;
        perlin_mirror_x: boolean;
        perlin_mirror_y: boolean;
        perlin_length_scale: bigint | number;
      },
      planet_default_stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      },
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      game_config_core: {
        max_natural_planet_level: bigint | number;
        perlin_threshold_1: bigint | number;
        perlin_threshold_2: bigint | number;
        perlin_threshold_3: bigint | number;
        init_perlin_min: bigint | number;
        init_perlin_max: bigint | number;
        biome_threshold_1: bigint | number;
        biome_threshold_2: bigint | number;
        planet_rarity: bigint | number;
        max_location_id: FieldLike;
      },
      planet_level_thresholds: { thresholds: (bigint | number)[] },
      space_junk_config: {
        space_junk_enabled: boolean;
        space_junk_limit: bigint | number;
        planet_level_junk: (bigint | number)[];
        abandon_speed_change_percent: bigint | number;
        abandon_range_change_percent: bigint | number;
      },
      planet_type_weights_tier_0: { weights: (bigint | number)[][] },
      planet_type_weights_tier_1: { weights: (bigint | number)[][] },
      planet_type_weights_tier_2: { weights: (bigint | number)[][] },
      planet_type_weights_tier_3: { weights: (bigint | number)[][] },
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_revealed_coords: {
        location_id: FieldLike;
        x: FieldLike;
        y: FieldLike;
        revealer: AztecAddressLike;
      },
      player_state: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_all_storage_addresses(config_addr: struct, world_addr: struct, player_addr: struct, planet_addr: struct, planet_revealed_coords_addr: struct, planet_events_addr: struct, planet_artifacts_addr: struct, arrivals_addr: struct, artifact_addr: struct, artifact_location_addr: struct) */
    set_all_storage_addresses: ((
      config_addr: AztecAddressLike,
      world_addr: AztecAddressLike,
      player_addr: AztecAddressLike,
      planet_addr: AztecAddressLike,
      planet_revealed_coords_addr: AztecAddressLike,
      planet_events_addr: AztecAddressLike,
      planet_artifacts_addr: AztecAddressLike,
      arrivals_addr: AztecAddressLike,
      artifact_addr: AztecAddressLike,
      artifact_location_addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_arrivals_storage_address(arrivals_storage_address: struct) */
    set_arrivals_storage_address: ((
      arrivals_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_location_storage_address(artifact_location_storage_address: struct) */
    set_artifact_location_storage_address: ((
      artifact_location_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_storage_address(artifact_storage_address: struct) */
    set_artifact_storage_address: ((
      artifact_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_config_storage_address(config_storage_address: struct) */
    set_config_storage_address: ((
      config_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_artifacts_storage_address(planet_artifacts_storage_address: struct) */
    set_planet_artifacts_storage_address: ((
      planet_artifacts_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_events_storage_address(planet_events_storage_address: struct) */
    set_planet_events_storage_address: ((
      planet_events_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_revealed_coords_storage_address(planet_revealed_coords_storage_address: struct) */
    set_planet_revealed_coords_storage_address: ((
      planet_revealed_coords_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_storage_address(planet_storage_address: struct) */
    set_planet_storage_address: ((
      planet_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_player_storage_address(player_storage_address: struct) */
    set_player_storage_address: ((
      player_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_world_storage_address(world_storage_address: struct) */
    set_world_storage_address: ((
      world_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** upgrade_planet(location: field, branch: integer, timestamp: integer, upgrade_config: struct, upgrade: struct, planet_state: struct, planet_artifacts_state: struct, planet_events_state: struct, arrivals: array, arrival_artifacts: array, arrival_artifact_locations: array, world: struct) */
    upgrade_planet: ((
      location: FieldLike,
      branch: bigint | number,
      timestamp: bigint | number,
      upgrade_config: {
        silver_cost_percent: bigint | number;
        max_total_level_nebula: bigint | number;
        max_total_level_space: bigint | number;
        max_total_level_deep_space: bigint | number;
        max_total_level_dead_space: bigint | number;
        max_branch_level: bigint | number;
      },
      upgrade: {
        pop_cap_multiplier: bigint | number;
        pop_gro_multiplier: bigint | number;
        range_multiplier: bigint | number;
        speed_multiplier: bigint | number;
        def_multiplier: bigint | number;
      },
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** withdraw_silver(location: field, silver_to_withdraw: integer, timestamp: integer, world_config: struct, planet_state: struct, planet_events_state: struct, arrivals: array, arrival_artifacts: array, arrival_artifact_locations: array, planet_artifacts_state: struct, player_state: struct, world: struct) */
    withdraw_silver: ((
      location: FieldLike,
      silver_to_withdraw: bigint | number,
      timestamp: bigint | number,
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      planet_state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      player_state: {
        init_timestamp: bigint | number;
        home_planet_id: FieldLike;
        last_reveal_timestamp: bigint | number;
        score: bigint | number;
        space_junk: bigint | number;
        space_junk_limit: bigint | number;
        claimed_ships: boolean;
        last_updated: bigint | number;
      },
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
