/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import MoveContractArtifactJson from "./move-Move.json" with { type: "json" };
export const MoveContractArtifact = loadContractArtifact(
  MoveContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Move;
 */
export class MoveContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, MoveContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): MoveContract {
    return Contract.at(address, MoveContract.artifact, wallet) as MoveContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<MoveContract>(
      PublicKeys.default(),
      wallet,
      MoveContractArtifact,
      (instance, wallet) => MoveContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<MoveContract>(
      publicKeys,
      wallet,
      MoveContractArtifact,
      (instance, wallet) => MoveContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MoveContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MoveContract["methods"][M]>
  ) {
    return new DeployMethod<MoveContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MoveContractArtifact,
      (instance, wallet) => MoveContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MoveContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      MoveContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "config_storage_address"
    | "world_storage_address"
    | "player_storage_address"
    | "planet_storage_address"
    | "planet_events_storage_address"
    | "planet_artifacts_storage_address"
    | "arrivals_storage_address"
    | "artifact_storage_address"
    | "artifact_location_storage_address"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      config_storage_address: {
        slot: new Fr(2n),
      },
      world_storage_address: {
        slot: new Fr(3n),
      },
      player_storage_address: {
        slot: new Fr(4n),
      },
      planet_storage_address: {
        slot: new Fr(5n),
      },
      planet_events_storage_address: {
        slot: new Fr(6n),
      },
      planet_artifacts_storage_address: {
        slot: new Fr(7n),
      },
      arrivals_storage_address: {
        slot: new Fr(8n),
      },
      artifact_storage_address: {
        slot: new Fr(9n),
      },
      artifact_location_storage_address: {
        slot: new Fr(10n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "config_storage_address"
      | "world_storage_address"
      | "player_storage_address"
      | "planet_storage_address"
      | "planet_events_storage_address"
      | "planet_artifacts_storage_address"
      | "arrivals_storage_address"
      | "artifact_storage_address"
      | "artifact_location_storage_address"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** move(source_loc: field, target_loc: field, target_perlin: integer, target_level: integer, max_dist: integer, x1: field, y1: field, x2: field, y2: field, pop_moved: integer, silver_moved: integer, moved_artifact_id: field, source_activated_artifact_id: field, target_activated_artifact_id: field, is_abandoning: boolean, timestamp: integer, snark_config: struct, planet_default_stats: struct, world_config: struct, game_config_core: struct, planet_level_thresholds: struct, space_junk_config: struct, planet_type_weights_tier_0: struct, planet_type_weights_tier_1: struct, planet_type_weights_tier_2: struct, planet_type_weights_tier_3: struct, artifacts_config: struct, source_planet: struct, source_planet_artifacts_state: struct, source_planet_events_state: struct, source_arrivals: array, source_arrival_artifacts: array, source_arrival_artifact_locations: array, target_planet: struct, target_planet_artifacts_state: struct, target_planet_events_state: struct, target_arrivals: array, target_arrival_artifacts: array, target_arrival_artifact_locations: array, world: struct, moved_artifact: struct, source_activated_artifact: struct, target_activated_artifact: struct) */
    move: ((
      source_loc: FieldLike,
      target_loc: FieldLike,
      target_perlin: bigint | number,
      target_level: bigint | number,
      max_dist: bigint | number,
      x1: FieldLike,
      y1: FieldLike,
      x2: FieldLike,
      y2: FieldLike,
      pop_moved: bigint | number,
      silver_moved: bigint | number,
      moved_artifact_id: FieldLike,
      source_activated_artifact_id: FieldLike,
      target_activated_artifact_id: FieldLike,
      is_abandoning: boolean,
      timestamp: bigint | number,
      snark_config: {
        disable_zk_checks: boolean;
        planethash_key: bigint | number;
        spacetype_key: bigint | number;
        biomebase_key: bigint | number;
        perlin_mirror_x: boolean;
        perlin_mirror_y: boolean;
        perlin_length_scale: bigint | number;
      },
      planet_default_stats: {
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_growth: bigint | number;
        silver_cap: bigint | number;
        barbarian_percentage: bigint | number;
      },
      world_config: {
        start_paused: boolean;
        time_factor_hundredths: bigint | number;
        spawn_rim_area: bigint | number;
        world_radius_locked: boolean;
        world_radius_min: bigint | number;
        location_reveal_cooldown: bigint | number;
        silver_score_value: bigint | number;
        planet_transfer_enabled: boolean;
        admin_can_add_planets: boolean;
      },
      game_config_core: {
        max_natural_planet_level: bigint | number;
        perlin_threshold_1: bigint | number;
        perlin_threshold_2: bigint | number;
        perlin_threshold_3: bigint | number;
        init_perlin_min: bigint | number;
        init_perlin_max: bigint | number;
        biome_threshold_1: bigint | number;
        biome_threshold_2: bigint | number;
        planet_rarity: bigint | number;
        max_location_id: FieldLike;
      },
      planet_level_thresholds: { thresholds: (bigint | number)[] },
      space_junk_config: {
        space_junk_enabled: boolean;
        space_junk_limit: bigint | number;
        planet_level_junk: (bigint | number)[];
        abandon_speed_change_percent: bigint | number;
        abandon_range_change_percent: bigint | number;
      },
      planet_type_weights_tier_0: { weights: (bigint | number)[][] },
      planet_type_weights_tier_1: { weights: (bigint | number)[][] },
      planet_type_weights_tier_2: { weights: (bigint | number)[][] },
      planet_type_weights_tier_3: { weights: (bigint | number)[][] },
      artifacts_config: {
        token_mint_end_timestamp: bigint | number;
        artifact_point_values: (bigint | number)[];
        photoid_activation_delay: bigint | number;
      },
      source_planet: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      source_planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      source_planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      source_arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      source_arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      source_arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      target_planet: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
      target_planet_artifacts_state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      target_planet_events_state: {
        events: { id: FieldLike }[];
        count: bigint | number;
        last_updated: bigint | number;
      },
      target_arrivals: {
        id: FieldLike;
        player: AztecAddressLike;
        from_planet: FieldLike;
        to_planet: FieldLike;
        pop_arriving: bigint | number;
        silver_moved: bigint | number;
        departure_time: bigint | number;
        arrival_time: bigint | number;
        arrival_type: bigint | number;
        carried_artifact_id: FieldLike;
        distance: bigint | number;
      }[],
      target_arrival_artifacts: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      }[],
      target_arrival_artifact_locations: {
        planet_id: FieldLike;
        voyage_id: FieldLike;
        last_updated: bigint | number;
      }[],
      world: {
        paused: boolean;
        radius: bigint | number;
        misc_nonce: bigint | number;
        next_change_block: bigint | number;
      },
      moved_artifact: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      },
      source_activated_artifact: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      },
      target_activated_artifact: {
        planet_discovered_on: FieldLike;
        rarity: bigint | number;
        planet_biome: bigint | number;
        minted_at_timestamp: bigint | number;
        discoverer: AztecAddressLike;
        artifact_type: bigint | number;
        activations: bigint | number;
        last_activated: bigint | number;
        last_deactivated: bigint | number;
        wormhole_to: FieldLike;
        owner: AztecAddressLike;
        controller: AztecAddressLike;
        last_updated: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_all_storage_addresses(config_addr: struct, world_addr: struct, player_addr: struct, planet_addr: struct, planet_events_addr: struct, planet_artifacts_addr: struct, arrivals_addr: struct, artifact_addr: struct, artifact_location_addr: struct) */
    set_all_storage_addresses: ((
      config_addr: AztecAddressLike,
      world_addr: AztecAddressLike,
      player_addr: AztecAddressLike,
      planet_addr: AztecAddressLike,
      planet_events_addr: AztecAddressLike,
      planet_artifacts_addr: AztecAddressLike,
      arrivals_addr: AztecAddressLike,
      artifact_addr: AztecAddressLike,
      artifact_location_addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_arrivals_storage_address(arrivals_storage_address: struct) */
    set_arrivals_storage_address: ((
      arrivals_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_location_storage_address(artifact_location_storage_address: struct) */
    set_artifact_location_storage_address: ((
      artifact_location_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_artifact_storage_address(artifact_storage_address: struct) */
    set_artifact_storage_address: ((
      artifact_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_config_storage_address(config_storage_address: struct) */
    set_config_storage_address: ((
      config_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_artifacts_storage_address(planet_artifacts_storage_address: struct) */
    set_planet_artifacts_storage_address: ((
      planet_artifacts_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_events_storage_address(planet_events_storage_address: struct) */
    set_planet_events_storage_address: ((
      planet_events_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_planet_storage_address(planet_storage_address: struct) */
    set_planet_storage_address: ((
      planet_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_player_storage_address(player_storage_address: struct) */
    set_player_storage_address: ((
      player_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_world_storage_address(world_storage_address: struct) */
    set_world_storage_address: ((
      world_storage_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
