/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import PlanetArtifactsStorageContractArtifactJson from "./planet_artifacts-PlanetArtifactsStorage.json" with { type: "json" };
export const PlanetArtifactsStorageContractArtifact = loadContractArtifact(
  PlanetArtifactsStorageContractArtifactJson as NoirCompiledContract,
);

export type PlanetArtifactsUpdate = {
  id: FieldLike;
  block_number: bigint | number;
  state: {
    ids: FieldLike[];
    count: bigint | number;
    last_updated: bigint | number;
  };
};

/**
 * Type-safe interface for contract PlanetArtifactsStorage;
 */
export class PlanetArtifactsStorageContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, PlanetArtifactsStorageContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PlanetArtifactsStorageContract {
    return Contract.at(
      address,
      PlanetArtifactsStorageContract.artifact,
      wallet,
    ) as PlanetArtifactsStorageContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PlanetArtifactsStorageContract>(
      PublicKeys.default(),
      wallet,
      PlanetArtifactsStorageContractArtifact,
      (instance, wallet) =>
        PlanetArtifactsStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<PlanetArtifactsStorageContract>(
      publicKeys,
      wallet,
      PlanetArtifactsStorageContractArtifact,
      (instance, wallet) =>
        PlanetArtifactsStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof PlanetArtifactsStorageContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PlanetArtifactsStorageContract["methods"][M]>
  ) {
    return new DeployMethod<PlanetArtifactsStorageContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PlanetArtifactsStorageContractArtifact,
      (instance, wallet) =>
        PlanetArtifactsStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PlanetArtifactsStorageContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      PlanetArtifactsStorageContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "authorized_map"
    | "authorized_index"
    | "authorized_list"
    | "authorized_count"
    | "state_roots"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      authorized_map: {
        slot: new Fr(2n),
      },
      authorized_index: {
        slot: new Fr(3n),
      },
      authorized_list: {
        slot: new Fr(4n),
      },
      authorized_count: {
        slot: new Fr(5n),
      },
      state_roots: {
        slot: new Fr(6n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "authorized_map"
      | "authorized_index"
      | "authorized_list"
      | "authorized_count"
      | "state_roots"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** add_authorized_contract(contract_address: struct) */
    add_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** add_authorized_contracts_batch(addresses: array, count: integer) */
    add_authorized_contracts_batch: ((
      addresses: AztecAddressLike[],
      count: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash(state: struct) */
    compute_state_hash: ((state: {
      ids: FieldLike[];
      count: bigint | number;
      last_updated: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash_unconstrained(state: struct) */
    compute_state_hash_unconstrained: ((state: {
      ids: FieldLike[];
      count: bigint | number;
      last_updated: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract(index: integer) */
    get_authorized_contract: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract_unconstrained(index: integer) */
    get_authorized_contract_unconstrained: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count() */
    get_authorized_count: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count_unconstrained() */
    get_authorized_count_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_default_state_unconstrained() */
    get_default_state_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root(id: field) */
    get_state_root: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root_unconstrained(id: field) */
    get_state_root_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized(addr: struct) */
    is_authorized: ((addr: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized_unconstrained(addr: struct) */
    is_authorized_unconstrained: ((
      addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized(id: field) */
    is_initialized: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized_unconstrained(id: field) */
    is_initialized_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** remove_authorized_contract(contract_address: struct) */
    remove_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set(id: field, state: struct) */
    set: ((
      id: FieldLike,
      state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify(id: field, state: struct) */
    verify: ((
      id: FieldLike,
      state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_hash(id: field, hash: field) */
    verify_hash: ((
      id: FieldLike,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_unconstrained(id: field, state: struct) */
    verify_unconstrained: ((
      id: FieldLike,
      state: {
        ids: FieldLike[];
        count: bigint | number;
        last_updated: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };

  public static get events(): {
    PlanetArtifactsUpdate: {
      abiType: AbiType;
      eventSelector: EventSelector;
      fieldNames: string[];
    };
  } {
    return {
      PlanetArtifactsUpdate: {
        abiType: {
          kind: "struct",
          fields: [
            {
              name: "id",
              type: {
                kind: "field",
              },
            },
            {
              name: "block_number",
              type: {
                kind: "integer",
                sign: "unsigned",
                width: 32,
              },
            },
            {
              name: "state",
              type: {
                kind: "struct",
                fields: [
                  {
                    name: "ids",
                    type: {
                      kind: "array",
                      length: 20,
                      type: {
                        kind: "field",
                      },
                    },
                  },
                  {
                    name: "count",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 32,
                    },
                  },
                  {
                    name: "last_updated",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 64,
                    },
                  },
                ],
                path: "types::storage::planet::PlanetArtifacts",
              },
            },
          ],
          path: "PlanetArtifactsStorage::PlanetArtifactsUpdate",
        },
        eventSelector: EventSelector.fromString("0x92832f28"),
        fieldNames: ["id", "block_number", "state"],
      },
    };
  }
}
