/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import PlanetStorageContractArtifactJson from "./planet-PlanetStorage.json" with { type: "json" };
export const PlanetStorageContractArtifact = loadContractArtifact(
  PlanetStorageContractArtifactJson as NoirCompiledContract,
);

export type PlanetUpdate = {
  id: FieldLike;
  block_number: bigint | number;
  state: {
    perlin: bigint | number;
    created_at: bigint | number;
    owner: AztecAddressLike;
    planet_level: bigint | number;
    planet_type: bigint | number;
    space_type: bigint | number;
    is_home_planet: boolean;
    is_initialized: boolean;
    destroyed: boolean;
    invader: AztecAddressLike;
    capturer: AztecAddressLike;
    invade_start_block: bigint | number;
    population_cap: bigint | number;
    population_growth: bigint | number;
    range: bigint | number;
    speed: bigint | number;
    defense: bigint | number;
    silver_cap: bigint | number;
    silver_growth: bigint | number;
    population: bigint | number;
    silver: bigint | number;
    upgrade_state_0: bigint | number;
    upgrade_state_1: bigint | number;
    upgrade_state_2: bigint | number;
    last_updated: bigint | number;
    pausers: bigint | number;
    energy_gro_doublers: bigint | number;
    silver_gro_doublers: bigint | number;
    hat_level: bigint | number;
    space_junk: bigint | number;
    has_tried_finding_artifact: boolean;
    prospected_block_number: bigint | number;
  };
};

/**
 * Type-safe interface for contract PlanetStorage;
 */
export class PlanetStorageContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, PlanetStorageContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PlanetStorageContract {
    return Contract.at(
      address,
      PlanetStorageContract.artifact,
      wallet,
    ) as PlanetStorageContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PlanetStorageContract>(
      PublicKeys.default(),
      wallet,
      PlanetStorageContractArtifact,
      (instance, wallet) => PlanetStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
  ) {
    return new DeployMethod<PlanetStorageContract>(
      publicKeys,
      wallet,
      PlanetStorageContractArtifact,
      (instance, wallet) => PlanetStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof PlanetStorageContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PlanetStorageContract["methods"][M]>
  ) {
    return new DeployMethod<PlanetStorageContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PlanetStorageContractArtifact,
      (instance, wallet) => PlanetStorageContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PlanetStorageContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      PlanetStorageContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "admin"
    | "authorized_map"
    | "authorized_index"
    | "authorized_list"
    | "authorized_count"
    | "state_roots"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      authorized_map: {
        slot: new Fr(2n),
      },
      authorized_index: {
        slot: new Fr(3n),
      },
      authorized_list: {
        slot: new Fr(4n),
      },
      authorized_count: {
        slot: new Fr(5n),
      },
      state_roots: {
        slot: new Fr(6n),
      },
    } as ContractStorageLayout<
      | "admin"
      | "authorized_map"
      | "authorized_index"
      | "authorized_list"
      | "authorized_count"
      | "state_roots"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** add_authorized_contract(contract_address: struct) */
    add_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** add_authorized_contracts_batch(addresses: array, count: integer) */
    add_authorized_contracts_batch: ((
      addresses: AztecAddressLike[],
      count: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash(state: struct) */
    compute_state_hash: ((state: {
      perlin: bigint | number;
      created_at: bigint | number;
      owner: AztecAddressLike;
      planet_level: bigint | number;
      planet_type: bigint | number;
      space_type: bigint | number;
      is_home_planet: boolean;
      is_initialized: boolean;
      destroyed: boolean;
      invader: AztecAddressLike;
      capturer: AztecAddressLike;
      invade_start_block: bigint | number;
      population_cap: bigint | number;
      population_growth: bigint | number;
      range: bigint | number;
      speed: bigint | number;
      defense: bigint | number;
      silver_cap: bigint | number;
      silver_growth: bigint | number;
      population: bigint | number;
      silver: bigint | number;
      upgrade_state_0: bigint | number;
      upgrade_state_1: bigint | number;
      upgrade_state_2: bigint | number;
      last_updated: bigint | number;
      pausers: bigint | number;
      energy_gro_doublers: bigint | number;
      silver_gro_doublers: bigint | number;
      hat_level: bigint | number;
      space_junk: bigint | number;
      has_tried_finding_artifact: boolean;
      prospected_block_number: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_state_hash_unconstrained(state: struct) */
    compute_state_hash_unconstrained: ((state: {
      perlin: bigint | number;
      created_at: bigint | number;
      owner: AztecAddressLike;
      planet_level: bigint | number;
      planet_type: bigint | number;
      space_type: bigint | number;
      is_home_planet: boolean;
      is_initialized: boolean;
      destroyed: boolean;
      invader: AztecAddressLike;
      capturer: AztecAddressLike;
      invade_start_block: bigint | number;
      population_cap: bigint | number;
      population_growth: bigint | number;
      range: bigint | number;
      speed: bigint | number;
      defense: bigint | number;
      silver_cap: bigint | number;
      silver_growth: bigint | number;
      population: bigint | number;
      silver: bigint | number;
      upgrade_state_0: bigint | number;
      upgrade_state_1: bigint | number;
      upgrade_state_2: bigint | number;
      last_updated: bigint | number;
      pausers: bigint | number;
      energy_gro_doublers: bigint | number;
      silver_gro_doublers: bigint | number;
      hat_level: bigint | number;
      space_junk: bigint | number;
      has_tried_finding_artifact: boolean;
      prospected_block_number: bigint | number;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_admin_unconstrained() */
    get_admin_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract(index: integer) */
    get_authorized_contract: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_contract_unconstrained(index: integer) */
    get_authorized_contract_unconstrained: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count() */
    get_authorized_count: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_authorized_count_unconstrained() */
    get_authorized_count_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_default_planet_unconstrained() */
    get_default_planet_unconstrained: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root(id: field) */
    get_state_root: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_state_root_unconstrained(id: field) */
    get_state_root_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized(addr: struct) */
    is_authorized: ((addr: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_authorized_unconstrained(addr: struct) */
    is_authorized_unconstrained: ((
      addr: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized(id: field) */
    is_initialized: ((id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_initialized_unconstrained(id: field) */
    is_initialized_unconstrained: ((
      id: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** remove_authorized_contract(contract_address: struct) */
    remove_authorized_contract: ((
      contract_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set(id: field, planet: struct) */
    set: ((
      id: FieldLike,
      planet: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((
      new_admin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify(id: field, state: struct) */
    verify: ((
      id: FieldLike,
      state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_hash(id: field, hash: field) */
    verify_hash: ((
      id: FieldLike,
      hash: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** verify_unconstrained(id: field, state: struct) */
    verify_unconstrained: ((
      id: FieldLike,
      state: {
        perlin: bigint | number;
        created_at: bigint | number;
        owner: AztecAddressLike;
        planet_level: bigint | number;
        planet_type: bigint | number;
        space_type: bigint | number;
        is_home_planet: boolean;
        is_initialized: boolean;
        destroyed: boolean;
        invader: AztecAddressLike;
        capturer: AztecAddressLike;
        invade_start_block: bigint | number;
        population_cap: bigint | number;
        population_growth: bigint | number;
        range: bigint | number;
        speed: bigint | number;
        defense: bigint | number;
        silver_cap: bigint | number;
        silver_growth: bigint | number;
        population: bigint | number;
        silver: bigint | number;
        upgrade_state_0: bigint | number;
        upgrade_state_1: bigint | number;
        upgrade_state_2: bigint | number;
        last_updated: bigint | number;
        pausers: bigint | number;
        energy_gro_doublers: bigint | number;
        silver_gro_doublers: bigint | number;
        hat_level: bigint | number;
        space_junk: bigint | number;
        has_tried_finding_artifact: boolean;
        prospected_block_number: bigint | number;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };

  public static get events(): {
    PlanetUpdate: {
      abiType: AbiType;
      eventSelector: EventSelector;
      fieldNames: string[];
    };
  } {
    return {
      PlanetUpdate: {
        abiType: {
          kind: "struct",
          fields: [
            {
              name: "id",
              type: {
                kind: "field",
              },
            },
            {
              name: "block_number",
              type: {
                kind: "integer",
                sign: "unsigned",
                width: 32,
              },
            },
            {
              name: "state",
              type: {
                kind: "struct",
                fields: [
                  {
                    name: "perlin",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "created_at",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 64,
                    },
                  },
                  {
                    name: "owner",
                    type: {
                      kind: "struct",
                      fields: [
                        {
                          name: "inner",
                          type: {
                            kind: "field",
                          },
                        },
                      ],
                      path: "aztec::protocol_types::address::aztec_address::AztecAddress",
                    },
                  },
                  {
                    name: "planet_level",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "planet_type",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "space_type",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "is_home_planet",
                    type: {
                      kind: "boolean",
                    },
                  },
                  {
                    name: "is_initialized",
                    type: {
                      kind: "boolean",
                    },
                  },
                  {
                    name: "destroyed",
                    type: {
                      kind: "boolean",
                    },
                  },
                  {
                    name: "invader",
                    type: {
                      kind: "struct",
                      fields: [
                        {
                          name: "inner",
                          type: {
                            kind: "field",
                          },
                        },
                      ],
                      path: "aztec::protocol_types::address::aztec_address::AztecAddress",
                    },
                  },
                  {
                    name: "capturer",
                    type: {
                      kind: "struct",
                      fields: [
                        {
                          name: "inner",
                          type: {
                            kind: "field",
                          },
                        },
                      ],
                      path: "aztec::protocol_types::address::aztec_address::AztecAddress",
                    },
                  },
                  {
                    name: "invade_start_block",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 32,
                    },
                  },
                  {
                    name: "population_cap",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "population_growth",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "range",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "speed",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "defense",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "silver_cap",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "silver_growth",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "population",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "silver",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "upgrade_state_0",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "upgrade_state_1",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "upgrade_state_2",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 8,
                    },
                  },
                  {
                    name: "last_updated",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 64,
                    },
                  },
                  {
                    name: "pausers",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "energy_gro_doublers",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "silver_gro_doublers",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "hat_level",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "space_junk",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 128,
                    },
                  },
                  {
                    name: "has_tried_finding_artifact",
                    type: {
                      kind: "boolean",
                    },
                  },
                  {
                    name: "prospected_block_number",
                    type: {
                      kind: "integer",
                      sign: "unsigned",
                      width: 32,
                    },
                  },
                ],
                path: "types::storage::planet::Planet",
              },
            },
          ],
          path: "PlanetStorage::PlanetUpdate",
        },
        eventSelector: EventSelector.fromString("0xc1220f26"),
        fieldNames: ["id", "block_number", "state"],
      },
    };
  }
}
