import dotenv from "dotenv";
import { appendFileSync, chmodSync, existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const bridgeDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
export const envPath = path.join(bridgeDir, ".env");
export const claimsDir = path.join(bridgeDir, "claims");
export const pxeDataDir = path.join(bridgeDir, ".store");

dotenv.config({ path: envPath, override: true });

export type BridgeConfig = {
  aztecNodeUrl: string;
  ethereumHost: string;
  l1PrivateKey?: `0x${string}`;
  l1Address?: `0x${string}`;
  gasBufferPercent: bigint;
  aztecAccount?: {
    salt: string;
    secretKey: string;
    signingKey: string;
    address?: string;
  };
};

function required(name: string): string {
  const value = process.env[name]?.trim();
  if (!value)
    throw new Error(`Missing ${name} in ${envPath}. Copy .env.example first.`);
  return value;
}

function optional(name: string): string | undefined {
  const value = process.env[name]?.trim();
  return value || undefined;
}

export function loadConfig(
  options: { requireL1Key?: boolean; requireAztecAccount?: boolean } = {},
): BridgeConfig {
  const l1PrivateKey = optional("L1_PRIVATE_KEY");
  if (options.requireL1Key && !l1PrivateKey) {
    throw new Error(
      "Missing L1_PRIVATE_KEY. Run `pnpm quote` first to create the L1 wallet.",
    );
  }
  if (l1PrivateKey && !/^0x[0-9a-fA-F]{64}$/.test(l1PrivateKey)) {
    throw new Error(
      "L1_PRIVATE_KEY must be a 0x-prefixed 32-byte hex private key.",
    );
  }

  const salt = optional("AZTEC_ACCOUNT_SALT");
  const secretKey = optional("AZTEC_ACCOUNT_SECRET_KEY");
  const signingKey = optional("AZTEC_ACCOUNT_SIGNING_KEY");
  const configured = [salt, secretKey, signingKey].filter(Boolean).length;
  if (configured > 0 && configured !== 3) {
    throw new Error(
      "AZTEC_ACCOUNT_SALT, AZTEC_ACCOUNT_SECRET_KEY, and AZTEC_ACCOUNT_SIGNING_KEY must be set together.",
    );
  }
  if (options.requireAztecAccount && configured !== 3) {
    throw new Error(
      "Missing Aztec account keys. Set AZTEC_ACCOUNT_SALT, AZTEC_ACCOUNT_SECRET_KEY, and AZTEC_ACCOUNT_SIGNING_KEY.",
    );
  }

  const rawBuffer = optional("ETH_GAS_BUFFER_PERCENT") ?? "25";
  if (!/^\d+$/.test(rawBuffer))
    throw new Error("ETH_GAS_BUFFER_PERCENT must be a non-negative integer.");

  return {
    aztecNodeUrl: required("AZTEC_NODE_URL"),
    ethereumHost: required("ETHEREUM_HOST"),
    l1PrivateKey: l1PrivateKey as `0x${string}` | undefined,
    l1Address: optional("L1_ADDRESS") as `0x${string}` | undefined,
    gasBufferPercent: BigInt(rawBuffer),
    aztecAccount:
      configured === 3
        ? {
            salt: salt!,
            secretKey: secretKey!,
            signingKey: signingKey!,
            address: optional("AZTEC_ACCOUNT_ADDRESS"),
          }
        : undefined,
  };
}

export function writeL1Wallet(wallet: {
  privateKey: `0x${string}`;
  address: `0x${string}`;
}): void {
  const content = [
    "",
    "# Generated by the bridge CLI. This is a hot wallet; never commit or share it.",
    `L1_PRIVATE_KEY=${wallet.privateKey}`,
    `L1_ADDRESS=${wallet.address}`,
    "",
  ].join("\n");
  if (existsSync(envPath)) appendFileSync(envPath, content, { mode: 0o600 });
  else writeFileSync(envPath, content, { mode: 0o600 });
  try {
    chmodSync(envPath, 0o600);
  } catch {
    // Windows does not support POSIX file modes.
  }
  process.env.L1_PRIVATE_KEY = wallet.privateKey;
  process.env.L1_ADDRESS = wallet.address;
}

export function writeL1Address(address: `0x${string}`): void {
  const content = `\n# Derived from L1_PRIVATE_KEY by the bridge CLI.\nL1_ADDRESS=${address}\n`;
  if (existsSync(envPath)) appendFileSync(envPath, content, { mode: 0o600 });
  else writeFileSync(envPath, content, { mode: 0o600 });
  try {
    chmodSync(envPath, 0o600);
  } catch {
    // Windows does not support POSIX file modes.
  }
  process.env.L1_ADDRESS = address;
}

export function writeAztecAccount(account: {
  salt: string;
  secretKey: string;
  signingKey: string;
  address: string;
}): void {
  const content = [
    "",
    "# Generated by the bridge CLI. These keys control the Aztec L2 account; never commit or share them.",
    `AZTEC_ACCOUNT_SALT=${account.salt}`,
    `AZTEC_ACCOUNT_SECRET_KEY=${account.secretKey}`,
    `AZTEC_ACCOUNT_SIGNING_KEY=${account.signingKey}`,
    `AZTEC_ACCOUNT_ADDRESS=${account.address}`,
    "",
  ].join("\n");
  if (existsSync(envPath)) appendFileSync(envPath, content, { mode: 0o600 });
  else writeFileSync(envPath, content, { mode: 0o600 });
  try {
    chmodSync(envPath, 0o600);
  } catch {
    // Windows does not support POSIX file modes.
  }
  process.env.AZTEC_ACCOUNT_SALT = account.salt;
  process.env.AZTEC_ACCOUNT_SECRET_KEY = account.secretKey;
  process.env.AZTEC_ACCOUNT_SIGNING_KEY = account.signingKey;
  process.env.AZTEC_ACCOUNT_ADDRESS = account.address;
}

export function writeNetworkAccounts(
  network: "mainnet" | "testnet",
  account: {
    l1PrivateKey: `0x${string}`;
    l1Address: `0x${string}`;
    salt: string;
    secretKey: string;
    signingKey: string;
    aztecAddress: string;
  },
): void {
  const prefix = network.toUpperCase();
  const keyNames = [
    `${prefix}_L1_PRIVATE_KEY`,
    `${prefix}_L1_ADDRESS`,
    `${prefix}_AZTEC_ACCOUNT_SALT`,
    `${prefix}_AZTEC_ACCOUNT_SECRET_KEY`,
    `${prefix}_AZTEC_ACCOUNT_SIGNING_KEY`,
    `${prefix}_AZTEC_ACCOUNT_ADDRESS`,
  ];
  if (keyNames.some((key) => process.env[key])) {
    throw new Error(
      `${network} account data already exists in ${envPath}. Refusing to overwrite private keys.`,
    );
  }
  const content = [
    "",
    `# Generated ${network} accounts. These are private keys; never commit or share them.`,
    `${prefix}_L1_PRIVATE_KEY=${account.l1PrivateKey}`,
    `${prefix}_L1_ADDRESS=${account.l1Address}`,
    `${prefix}_AZTEC_ACCOUNT_SALT=${account.salt}`,
    `${prefix}_AZTEC_ACCOUNT_SECRET_KEY=${account.secretKey}`,
    `${prefix}_AZTEC_ACCOUNT_SIGNING_KEY=${account.signingKey}`,
    `${prefix}_AZTEC_ACCOUNT_ADDRESS=${account.aztecAddress}`,
    "",
  ].join("\n");
  if (existsSync(envPath)) appendFileSync(envPath, content, { mode: 0o600 });
  else writeFileSync(envPath, content, { mode: 0o600 });
  try {
    chmodSync(envPath, 0o600);
  } catch {
    // Windows does not support POSIX file modes.
  }
  for (const line of content.split("\n")) {
    const equals = line.indexOf("=");
    if (equals > 0) process.env[line.slice(0, equals)] = line.slice(equals + 1);
  }
}
