[package]
name = "core"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v4.0.0-devnet.2-patch.1", directory = "aztec" }

types = { path = "../../types" }
config = { path = "../../config" }
libs={ path = "../../libs" }
circuits = { path = "../../circuits" }

world_storage = { path = "../../storage/world" }
player_storage = { path = "../../storage/player" }
planet_storage = { path = "../../storage/planet" }
planet_revealed_coords_storage = { path = "../../storage/planet_revealed_coords" }
planet_events_storage = { path = "../../storage/planet_events" }
planet_artifacts_storage = { path = "../../storage/planet_artifacts" }
artifact_storage = { path = "../../storage/artifact" }
artifact_location_storage = { path = "../../storage/artifact_location" }
arrival_storage = { path = "../../storage/arrival" }