[workspace]
members = [
    "types",
    "config",
     "circuits",
     "libs",
    "storage/planet",
    "storage/planet_revealed_coords",
    "storage/planet_events",
    "storage/planet_artifacts",
    "storage/artifact",
    "storage/artifact_location",
    "storage/arrival",
    "storage/player",
    "storage/world",
    "system/admin",
    "system/core",
    "system/move",
    "system/artifact",
    "system/artifact_ext",
]

# [dependencies]
# aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v3.0.0-devnet.6-patch.1", directory="aztec" }