[package]
name = "artifact"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.0.1", directory="aztec" }
macros = { path = "../../macros" }
types = { path = "../../types" }
